### ISSUE TITLE
Installation steps for Raspberry Pi

### ISSUE THREAD

**Issue by tchelomgf** [fralalonde/autoroute#1]
Hi, first of all, congrats, it´s great, working very well.

Just to add setup steps for begginers (like me):

cd ~
git clone https://github.com/fralalonde/autoroute
cd autoroute
cp autoroute.conf my.conf 
aconnect -l                 **_(get device names)_**
sudo nano my.conf    **_(edit your configurations using device names)_**
sudo python3 autoroute install
sudo cp my.conf /etc/autoroute.conf
sudo reboot

**Comment by fralalonde** [comment]
The timing of this first issue is funny, as I've myself reinstalled `autoroute` on my Pi for the first time since I finished it and came to the same conclusion as you did... The installation manual is missing! 

Your installation recipe is good, I'll paste it as it is in the `README` for now. I may change a thing or two later:
- A github hosted .zip release would remove the git requirement
- The `install` command should reload `udev` so that no reboot is required

**Comment by tchelomgf** [comment]
Great!
